/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufc.ck017.mmjc.lexer;

@SuppressWarnings("serial")
public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
